version: '3.3'
services:
  backend:
    ports: 
      - 3000:3005
    restart: unless-stopped
    build: ./packages/backend
  
  frontend:
    ports:
      - 3001:3000
    environment:
      - NUXT_PUBLIC_BACKEND_HOST=http://localhost:3000
    build: ./packages/frontend